#!/bin/bash
yum update -y
yum groups install -y "Basic Web Server"
yum install -y wget certbot python2-certbot-apache httpd
systemctl start httpd
systemctl enable httpd
systemctl status httpd
firewall-cmd --permanent --add-service=http --add-service=https ; firewall-cmd --reload ; firewall-cmd --list-all
wget http://sourceforge.net/projects/guacamoleinstallscript/files/CentOS/guacamole-install-script.sh
sudo chmod +x guacamole-install-script.sh
sudo ./guacamole-install-script.sh
sudo systemctl restart httpd
sudo systemctl restart guacd