#!/bin/bash
#INSTALLING GUACAMOLE ON CENTOS 7

yum update -y
yum groups install -y "Basic Web Server"
yum install -y wget certbot python2-certbot-apache httpd
systemctl start httpd
systemctl enable httpd
systemctl status httpd
firewall-cmd --permanent --add-service=http --add-service=https ; firewall-cmd --reload ; firewall-cmd --list-all
wget http://sourceforge.net/projects/guacamoleinstallscript/files/CentOS/guacamole-install-script.sh
sudo chmod +x guacamole-install-script.sh
sudo ./guacamole-install-script.sh
sudo systemctl restart httpd
sudo systemctl restart guacd

# at this point you should installed guacamole without ssl certificate now you do the following steps

#Replace guacamole.example.com with your domain name.
sudo vim /etc/httpd/conf.d/guacamole.conf
_________________________________________________
<VirtualHost *:443>
    ServerName guacamole.cevdetabbas.com

    # SSL Certificate Configuration
    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/guacamole.cevdetabbas.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/guacamole.cevdetabbas.com/privkey.pem

    # ... Other Guacamole configurations ...

    ProxyPass / http://localhost:8080/guacamole/
    ProxyPassReverse / http://localhost:8080/guacamole/
</VirtualHost>
_________________________________________________


# Obtain SSL Certificate: Replace guacamole.example.com with your actual domain.
sudo certbot certonly --webroot -w /var/www/html -d guacamole.cevdetabbas.com


# Update Guacamole Configuration: Uncomment or add the following lines:
sudo nano /etc/guacamole/guacamole.properties
_________________________________________________
guacd-ssl: true
guacd-hostname: localhost
guacd-port: 4822
_________________________________________________


# Restart Services:
sudo systemctl restart httpd
sudo systemctl restart guacd


# Automate Certificate Renewal:
sudo crontab -e
_________________________________________________
0 0,12 * * * certbot renew --post-hook "systemctl reload httpd"
_________________________________________________










_________________________________________________
<VirtualHost *:80>
  ServerName g3.cevdetabbas.com
  Redirect permanent / https://g3.cevdetabbas.com/
</VirtualHost>

<VirtualHost *:443>
    ServerName g3.cevdetabbas.com

    # SSL Certificate Configuration
    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/g3.cevdetabbas.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/g3.cevdetabbas.com/privkey.pem

    # ... Other Guacamole configurations ...

    ProxyPass / http://localhost:8080/guacamole/
    ProxyPassReverse / http://localhost:8080/guacamole/
</VirtualHost>
_________________________________________________


# Obtain SSL Certificate: Replace guacamole.example.com with your actual domain.
sudo certbot certonly --webroot -w /var/www/html -d g3.cevdetabbas.com


# Update Guacamole Configuration: Uncomment or add the following lines:
sudo vim /etc/guacamole/guacamole.properties
_________________________________________________
guacd-ssl: true
guacd-hostname: localhost
guacd-port: 4822
_________________________________________________


# Restart Services:
sudo systemctl restart httpd
sudo systemctl restart guacd


# Automate Certificate Renewal:
sudo crontab -e
_________________________________________________
0 0,12 * * * certbot renew --post-hook "systemctl reload httpd"
_________________________________________________
